add linux build to github actions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -37,14 +37,59 @@ jobs:
         with:
           name: windows-installer
           path: ${{ env.installer_path }}
+
+  linux-build:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+      
+      - name: Set up Docker
+        run: |
+          sudo apt update
+          sudo apt install ca-certificates curl
+          sudo install -m 0755 -d /etc/apt/keyrings
+          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+          sudo chmod a+r /etc/apt/keyrings/docker.asc
+          echo \
+            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
+            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+          sudo apt update
+          sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+          sudo systemctl start docker
+          
+      - name: Pull latest Fedora image
+        run: docker pull fedora:latest
+        
+      - name: Build and Test in Container
+        run: |
+          docker run --rm -v ${{ github.workspace }}:/src fedora:latest bash -c '
+            dnf install -y \
+              gtk4-devel \
+              glib2-devel\
+              libadwaita-devel \
+              pkg-config \
+              cmake \
+              ninja-build \
+              rust &&\
+              cargo\
+            cd /src && \
+            mkdir -p build && \
+            cd build && \
+            cmake -G "Ninja" .. && \
+            cmake --build . && \
+            if [ ! -d "bin" ]; then
+              echo "bin directory not found in build/"
+              exit 1
+            fi && \
+            ls -la bin/'
           
   flatpak-manifest:
+    needs: [linux-build]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-
-      - name: Set Pkg Config Path
-        run: export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH"
 
       - name: Install System Dependencies
         run: |
